version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html:ro  # Mount source code as read-only

  php:
    image: hello-php
    volumes:
      - ./src:/var/www/html  # Mount source code