version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hello-php
    restart: unless-stopped

  web:
    image: nginx:1.27-alpine
    container_name: hello-nginx
    ports:
      - "8080:80"            # host‑port -> container‑port
    volumes:
      - ./src:/var/www/html        # hot‑reload during dev
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped
