name: PHP-Hello-World CI  (reuses template)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    uses: nirajan-devops/ci-workflows/.github/workflows/php.yml@main
    with:
      php-version: '8.3'          # optional; overrides default
      working-dir: '.'  # path to the code to test
