name: Build & Deploy PHP Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Build PHP image
        run: docker build -t hello-php -f php.Dockerfile .

      - name: Save & compress Docker image
        run: docker save hello-php | gzip > hello-php.tar.gz

      - name: Verify local files
        run: |
          echo "Repository contents:"
          ls -R
          echo "Checking required files:"
          [ -f docker-compose.yml ] || exit 1
          [ -f nginx/default.conf ] || exit 1
          [ -f src/index.php ] || exit 1
          [ -f hello-php.tar.gz ] || exit 1

      - name: Copy configuration files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml,nginx/default.conf,hello-php.tar.gz"
          target: /home/${{ secrets.USERNAME }}/deploy
          overwrite: true

      - name: Copy PHP source code to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "src/"
          target: /home/${{ secrets.USERNAME }}/deploy/
          overwrite: true

      - name: Deploy application on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set up directory permissions
            sudo chown -R $USER:$USER /home/$USER/deploy
            chmod -R 755 /home/$USER/deploy
            
            # Verify files on server
            echo "Deployment directory contents:"
            ls -la ~/deploy/
            echo "Source files:"
            ls -la ~/deploy/src/
            [ -f ~/deploy/src/index.php ] || { echo "index.php missing!"; exit 1; }
            
            # Install Docker if missing
            if ! command -v docker >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER
            fi
            
            # Install Docker Compose v2 if missing
            if ! docker compose version >/dev/null 2>&1; then
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -sSL \
                https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi
            
            # Load Docker image
            gunzip -c ~/deploy/hello-php.tar.gz | sudo docker load
            
            # Start containers
            cd ~/deploy
            sudo docker compose up -d --build
            
            # Verify containers are running
            echo "Container status:"
            sudo docker compose ps
            echo "Nginx logs:"
            sudo docker compose logs nginx
            echo "PHP logs:"
            sudo docker compose logs php