name: Deploy React App via Docker

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hello-php .

      - name: Save Docker image to tar
        run: docker save hello-php -o hello-php.tar

      - name: Copy image to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "hello-php.tar"
          target: "/home/${{ secrets.USERNAME }}/"
          tar_dereference: false
          strip_components: false
          overwrite: true
          rm: false

      - name: Install Docker and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if it's not present
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi

            cd /home/${{ secrets.USERNAME }}

            echo "Loading Docker image..."
            ls -lh hello-php.tar
            sudo docker load -i hello-php.tar

            echo "Stopping existing container if running..."
            sudo docker stop hello-php || true
            sudo docker rm hello-php || true

            echo "Running new hello-php container..."
            sudo docker run -d -p 8080:80 --name hello-php hello-php
