name: Duild & Deploy (two-container stack)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build php image
        run: docker build -t hello-php .

      - name: Save Docker image to tar
        run: docker save hello-php -o hello-php.tar

      - name: Copy image to EC2 via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            ./docker-compose.yml
            ./nginx/default.conf
            ./hello-php.tar
          target: "/home/${{ secrets.USERNAME }}/"
          tar_dereference: false
          strip_components: false
          overwrite: true
          rm: false

      - name: Install Docker and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Install Docker if it's not present
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            fi
            if ! docker compose version >/dev/null 2>&1; then
              sudo curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose  
            fi

            # Load the freshly‑built PHP image
            cd /home/${{ secrets.USERNAME }}

            echo "Loading Docker image..."
            ls -lh hello-php.tar
            sudo docker load -i hello-php.tar

            # Start (or update) the stack
            sudo docker compose pull nginx:1.27-alpine || true
            sudo docker compose up -d    # will recreate only changed services

            sudo docker compose ps

           

           
