name: Build & Deploy PHP Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Build PHP image
        run: docker build -t hello-php -f php.Dockerfile .

      - name: Save & compress Docker image
        run: docker save hello-php | gzip > hello-php.tar.gz

      - name: Verify local files
        run: |
          ls -R
          [ -f docker-compose.yml ] || exit 1
          [ -f nginx/default.conf ] || exit 1
          [ -f src/index.php ] || exit 1
          [ -f hello-php.tar.gz ] || exit 1

      - name: Prepare directory structure on EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/deploy/src
            chmod -R 755 ~/deploy

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            docker-compose.yml
            nginx/default.conf
            hello-php.tar.gz
            src/index.php
          target: /home/${{ secrets.USERNAME }}/deploy/
          overwrite: true

      - name: Deploy application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Verify files
            ls -la ~/deploy/
            [ -f ~/deploy/src/index.php ] || { echo "index.php missing!"; exit 1; }
            
            # Docker setup
            if ! command -v docker >/dev/null; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
              sudo usermod -aG docker $USER
            fi
            
            if ! docker compose version >/dev/null 2>&1; then
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -sSL \
                https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi
            
            # Load and deploy
            gunzip -c ~/deploy/hello-php.tar.gz | sudo docker load
            cd ~/deploy
            sudo docker compose up -d --build
            sudo docker compose ps